name: Build SpaceWarp

on:
  push:
    branches: ['build']
  workflow_dispatch:

permissions: write-all

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with: 
          filepath: './ISS/script.iss'

      - name: Create Artifact (portable)
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./dist/

      - name: Create Artifact (installer)
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: ./ISS/Output/
  mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller py2app
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - name: Create Folder
        run: mkdir pyinstallerVersion

      - name: Move Files
        run: cp -R dist/* pyinstallerVersion

      - name: Delete Folder
        run: rm -r dist

      - name: Download Required Files
        run: curl -LOk https://github.com/ForkPrince/SpaceWarp/archive/refs/heads/mac.zip

      - name: Extract Required Files
        run: unzip mac.zip

      - name: Move Files
        run: cp -R SpaceWarp-mac/* .

      - name: Delete Folder
        run: rm -r SpaceWarp-mac

      - name: Build App
        run: python setup.py py2app

      - name: Create Artifact (pyinstaller)
        uses: actions/upload-artifact@v3
        with:
          name: mac-pyinstaller
          path: ./pyinstallerVersion/

      - name: Create Artifact (py2app)
        uses: actions/upload-artifact@v3
        with:
          name: mac-py2app
          path: ./dist/
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller

      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - name: Build Pyxel App
        run: pyxel package ./ ./main.py

      - name: Build Web App
        run: pyxel app2html ./SpaceWarp-main.pyxapp

      - name: Create Artifact (web)
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: ./SpaceWarp-main.html

      - name: Create Artifact (linux)
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./dist/
