name: Build and Release Pyxel Game

on:
  push:
    branches:
      - build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Packages
        run: sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

      - name: Install Pyxel
        run: pip install pyxel

      - name: Build and Package
        run: pyxel package ./ main.py

      - name: Build EXE
        run: pyxel app2exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./SpaceWarp.exe
