name: Build SpaceWarp

on:
  push:
    branches:
      - build
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Packages
        run: sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0 p7zip-full p7zip-rar

      - name: Install Pyxel
        run: pip install pyxel

      - name: Install Pyinstaller
        run: pip install pyinstaller 

      - name: Build EXE
        run: pyinstaller main.py --add-data "mask.json;./" --add-data "assets;assets" -w --clean -n SpaceWarp -y

      - name: Package Compiled Files
        run: 7z a -t7z -r SpaceWarp.7z D:/a/SpaceWarp/SpaceWarp/dist/main

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: /SpaceWarp/dist/main/SpaceWarp.7z
