name: Build SpaceWarp

on:
  push:
    branches: ['build']
  workflow_dispatch:

permissions: write-all

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./dist/
  windows-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with: 
          filepath: './ISS/script.iss'

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: ./ISS/Output/
  mac-pyinstaller:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-pyinstaller
          path: ./dist/
  mac-py2app:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel py2app
        
      - name: Download Required Files
        run: curl -LOk https://github.com/ForkPrince/SpaceWarp/archive/refs/heads/mac.zip

      - name: Extract Required Files
        run: unzip mac.zip
        
      - name: See directory
        run: ls
        
      - name: Build App
        run: python setup.py py2app

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-py2app
          path: ./dist/
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: pip install pyxel pyinstaller
        
      - name: Build App
        run: pyinstaller SpaceWarp.spec

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./dist/
