name: Build and Release Pyxel Game

on:
  push:
    branches:
      - build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Wam25/SpaceWarp

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Packages
        run: sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

      - name: Install Pyxel
        run: pip install pyxel

      - name: Build and Package
        run: pyxel package ./ main.py

      - name: Install Pyinstaller
        run: pip install pyinstaller 

      - name: Build EXE
        run: pyxel app2exe ./SpaceWarp.pyxapp

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SpaceWarp.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: spacewarp
          name: Automated Release
          replacesArtifacts: true
          allowUpdates: true
